name: Tests API

on:
  push:
    branches:
      - main

jobs:
  test: 
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: Integration tests with pytest
      run: |
        cd api
        pytest -vv --cov=api --cov-report=xml --cov-report=html

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: pytest_html_report
        path: pytest_html_report.html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v3
      with:
        name: html-coverage-report
        path: htmlcov/
    